name: BE CD

on:
  push:
    branches:
      - main
  # workflow_run:
  #   workflows: ['React Frontend CI'] # ci.yml에서 설정한 이름과 동일해야 함
  #   type s:
  #     - completed

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build the Spring application
        run: ./gradlew build -x test # Gradle로 빌드 (테스트 제외)

      - name: Kill existing Java processes (if running)
        run: |
          # PowerShell로 프로세스 확인 및 종료
          $process = Get-Process | Where-Object { $_.ProcessName -eq "java" }
          if ($process) {
            Write-Host "Killing existing Java process..."
            Stop-Process -Id $process.Id
          } else {
            Write-Host "No existing Java process found."
          }

      - name: Start Spring server using Java (Background)
        run: |
          # Start the Spring Boot application in the background
          start /b java -jar build/libs/demo-0.0.1-SNAPSHOT.jar
          exit 0
