name: BE CD

on:
  push:
    branches:
      - main
  # workflow_run:
  #   workflows: ['React Frontend CI'] # ci.yml에서 설정한 이름과 동일해야 함
  #   type s:
  #     - completed

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build the Spring application
        run: ./gradlew build -x test # Gradle로  빌드 (테스트 제외)

      - name: Kill existing Java processes (if running)
        run: |
          # PowerShell로 프로세스 확인 및 종료
          $process = Get-Process | Where-Object { $_.ProcessName -eq "java" }
          if ($process) {
            Write-Host "Killing existing Java process..."
            Stop-Process -Id $process.Id
          } else {
            Write-Host "No existing Java process found."
          }

      - name: Execute start-server.ps1 script
        run: |
          Start-Job -ScriptBlock {
          java -jar build/libs/demo-0.0.1-SNAPSHOT.jar
          }
          Start-Sleep -Seconds 30  # Optional, to wait for the app to start
          # PowerShell 스크립트 실행
          # echo "Current directory: $PWD"
          # powershell -ExecutionPolicy Bypass -File ./start-server.ps1
