name: BE CD

on:
  push:
    branches:
      - main
  # workflow_run:
  #   workflows: ['React Frontend CI'] # ci.yml에서 설정한 이름과 동일해야 함
  #   type s:
  #     - completed

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build the Spring application
        run: ./gradlew clean build -x test # Gradle로  빌드 (테스트 제외)

      - name: Docker Build
        run: docker build -t my-server-image .

      - name: Restart Container
        run: |
          docker stop my-server || true
          docker rm my-server || true
          docker run -d -p 8080:8080 --name my-server my-server-image
